name: Upload to App Store

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload IPA to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: app.ipa
          issuer-id: ${{ 7b772343-a94b-4c82-8019-4ef7e4e70f38 }}
          api-key-id: ${{ VL592D9JB6}}
          api-private-key:
-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4waS24x3G9io3Jop
IQPwVYO7w0XSpabEioJunz1rPF2gCgYIKoZIzj0DAQehRANCAASN3VtrZ7BKLjGk
+we6kyxhPfqvJyB4k0aGM3VeXbcWqhzSM4JZ+VNagIRToDHE0B35bpjyJ/bxa+5y
XzPjJR1b
-----END PRIVATE KEY-----
